### ISSUE TITLE
Is there a way to change the title of a whole repo?

### ISSUE THREAD

**Issue by RebeccaSchatz** [CoderDojoTC/volunteer-resources#2]
Is there a way to change the title of a whole repo?  I'd like to rename this one coordinator-resources instead of volunteer-resources.   I could always create a new repo with a new name and then delete the old one, but it would be slicker if there was a way to just rename.   Thanks!

**Comment by rrazor** [comment]
Click on the repository, and then click on "Settings" in the right-hand navigation. The repository name is the first option.
